from building import *

cwd = GetCurrentDir()
src = []
path = [cwd, cwd + '/../stepper_drv']

if GetDepend('BSP_USING_STEPPER_OPEN_LOOP'):
    src += Glob('*.c')

group = DefineGroup('stepper_ol', src, depend=['BSP_USING_STEPPER_OPEN_LOOP'], CPPPATH=path)
Return('group')
