from building import *

cwd = GetCurrentDir()
src = []
path = [cwd, cwd + '/../stepper_drv']

if GetDepend('BSP_USING_STEPPER_SPEED_LOOP'):
    src += Glob('*.c')

group = DefineGroup('speed_loop', src, depend=['BSP_USING_STEPPER_SPEED_LOOP'], CPPPATH=path)
Return('group')
